# Generated by Django 5.1.3 on 2024-11-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_designrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='design_requests/', verbose_name='Фото помещения'),
        ),
    ]
